name: Check Functions

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd functions && npm install
      - name: Linter check
        run: cd functions && npm run lint
      - name: Testing check
        run: cd functions && npm run test
